# Generated by Django 4.2 on 2023-04-06 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0002_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dengue.municipal'),
        ),
    ]
