# Generated by Django 4.2 on 2023-04-06 03:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0003_barangay_municipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(help_text='Date format: YYYY-MM-DD example: (2000-01-06)')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('latitude', models.FloatField(blank=True, help_text='Enter latitude here (e.g. 37.7749)(Optional)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Enter longitude here (e.g. 37.7749)(Optional)', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dengue.barangay')),
                ('municipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dengue.municipal')),
            ],
        ),
    ]
