# Generated by Django 4.2 on 2023-04-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0005_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipal',
            name='code',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
