# Generated by Django 4.2 on 2023-05-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0008_alter_case_date_alter_case_dengue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='municipal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dengue.municipal'),
        ),
    ]
