# Generated by Django 4.2 on 2023-06-09 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dengue', '0009_alter_barangay_municipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dengue.municipal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
