# Generated by Django 4.2 on 2023-06-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0011_alter_usermunicipal_municipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermunicipal',
            name='municipal',
            field=models.ForeignKey(blank=True, help_text='If not superuser', null=True, on_delete=django.db.models.deletion.CASCADE, to='dengue.municipal'),
        ),
    ]
