# Generated by Django 4.2 on 2023-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0012_alter_usermunicipal_municipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='suffix',
            field=models.CharField(blank=True, choices=[('Sr', 'Sr'), ('Jr', 'Jr'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateTimeField(help_text='Date format: YYYY-MM-DD example: (2000-01-06)', verbose_name='Date'),
        ),
    ]
