# Generated by Django 4.2 on 2023-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0013_resident_suffix_alter_case_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateField(help_text='Date format: YYYY-MM-DD example: (2000-01-06)', verbose_name='Date'),
        ),
    ]
