# Generated by Django 4.2 on 2023-07-01 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0015_case_created_at_case_updated_at_alter_resident_geom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
