# Generated by Django 4.2 on 2023-08-26 10:29

import dengue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0016_resident_created_at_resident_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='ar',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit]),
            preserve_default=False,
        ),
    ]
