# Generated by Django 4.2 on 2023-08-26 10:30

import dengue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0017_barangay_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='ar',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='AR'),
        ),
    ]
