# Generated by Django 4.2 on 2023-08-26 10:33

import dengue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0018_alter_barangay_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='i',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='I'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barangay',
            name='ma',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='MA'),
            preserve_default=False,
        ),
    ]
