# Generated by Django 4.2 on 2023-08-26 10:39

import dengue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0019_barangay_i_barangay_ma'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='is_seosonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barangay',
            name='seasonal_ar',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='SEASONAL_AR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barangay',
            name='seasonal_i',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='SEASONAL_I'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barangay',
            name='seasonal_ma',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='SEASONAL_MA'),
            preserve_default=False,
        ),
    ]
