# Generated by Django 4.2 on 2023-08-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0020_barangay_is_seosonal_barangay_seasonal_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='is_seosonal',
        ),
        migrations.AddField(
            model_name='barangay',
            name='is_seasonal',
            field=models.BooleanField(default=False, verbose_name='SEASONALITY'),
        ),
    ]
