# Generated by Django 4.2 on 2023-08-26 10:55

import dengue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0021_remove_barangay_is_seosonal_barangay_is_seasonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='seasonal_cycle',
            field=models.IntegerField(choices=[(7, 7), (52, 52)], default=52, verbose_name='SEASONAL CYCLE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barangay',
            name='seasonal_ar',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='SEASONAL AR'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='seasonal_i',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='SEASONAL I'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='seasonal_ma',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='SEASONAL MA'),
        ),
    ]
