# Generated by Django 4.2 on 2023-08-27 11:20

import dengue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0023_alter_barangay_is_seasonal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='ar',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='AR(p)'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='i',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='I(d)'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='is_seasonal',
            field=models.BooleanField(default=False, help_text='Checking this will use the Seasonal Component of SARIMA', verbose_name='Seasonality'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='ma',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='MA(q)'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='seasonal_ar',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='Seasonal AR(P)'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='seasonal_cycle',
            field=models.IntegerField(choices=[(7, 7), (52, 52)], verbose_name='Seasonal Cycle(S)'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='seasonal_i',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='Seasonal I(D)'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='seasonal_ma',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0), dengue.models.validate_single_digit], verbose_name='Seasonal MA(Q)'),
        ),
    ]
