# Generated by Django 4.2 on 2023-10-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0024_alter_barangay_ar_alter_barangay_i_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='seasonal_cycle',
        ),
    ]
