# Generated by Django 4.2 on 2023-10-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0025_remove_barangay_seasonal_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='is_auto_arima',
            field=models.BooleanField(default=True, help_text='Checking this will use Auto ARIMA and ignore all the input belows', verbose_name='Auto ARIMA'),
        ),
    ]
