# Generated by Django 4.2 on 2023-10-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue', '0027_alter_barangay_is_auto_arima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='is_seasonal',
            field=models.BooleanField(default=False, help_text='Checking this will use the Seasonal ARIMA', verbose_name='Use Seasonal ARIMA'),
        ),
    ]
